import type { Metadata } from "next";
import localFont from 'next/font/local'
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import Header from './header'
import Footer from './footer'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const myFont = localFont({
    src: [
        {
            path: './fonts/gothamrnd_bold.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/gothamrnd_bolditalic.woff2',
            weight: '700',
            style: 'italic',
        },
        {
            path: './fonts/gothamrnd_medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: './fonts/gothamrnd_mediumitalic.woff2',
            weight: '500',
            style: 'italic',
        },
        {
            path: './fonts/gothamrnd_book.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/gothamrnd_bookitalic.woff2',
            weight: '400',
            style: 'italic',
        },
        {
            path: './fonts/gothamrnd_light.woff2',
            weight: '300',
            style: 'normal',
        },
        {
            path: './fonts/gothamrnd_lightitalic.woff2',
            weight: '300',
            style: 'italic',
        },
    ],
})

export default async function Root({ children, params: { locale } }: { children: React.ReactNode, params: { locale: string  }}) {
    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={myFont.className}>
                <NextIntlClientProvider messages={messages}>
                    <Header />
                    {children}
                    <Footer />
                </NextIntlClientProvider>
            </body>
        </html>
    )
}